name: Upload to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: conholdate/cms.admin.containerize.com  # replace with your private repo
        token: ${{ secrets.GH_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # replace with your AWS region

    - name: Sync templates folder to S3
      run: aws s3 sync templates/ s3://cms.admin.containerize.com/ --delete
